name: End-to-End tests
on:
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  e2e_user_features:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
          architecture: 'x64'
      - name: Setup python by installing wheel
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: pip install wheel==0.35.0
      - name: Install third party
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: python -m scripts.install_third_party_libs
      - name: Install chrome
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: python -m scripts.install_chrome_for_ci
      - name: Install ffmpeg
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: sudo apt install ffmpeg
      - name: Run e2e preferences test
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: xvfb-run -a python -m scripts.run_e2e_tests --suite="preferences" --prod_env
      - name: Run e2e subscriptions test
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: xvfb-run -a python -m scripts.run_e2e_tests --skip-install --skip-build --suite="subscriptions" --prod_env
      - name: Run e2e wipeout test
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: xvfb-run -a python -m scripts.run_e2e_tests --skip-install --skip-build --suite="wipeout" --prod_env
      - name: Uploading protractor-screenshots as Artifacts
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false && always()
        uses: actions/upload-artifact@v2
        with:
          name: protractor-screenshots
          path: /home/runner/work/oppia/protractor-screenshots
      - name: Uploading protractor-video as Artifacts
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false && always()
        uses: actions/upload-artifact@v2
        with:
          name: protractor-video
          path: /home/runner/work/oppia/oppia/core/protractor-video
