name: End-to-End tests
on:
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  e2e_miscellaneous_tests:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - uses: ./.github/actions/merge
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: /home/runner/work/oppia/yarn_cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: ./.github/actions/install-oppia-dependencies
      - id: check-risk
        name: Check if PR is low-risk
        uses: ./.github/actions/check-if-pr-is-low-risk
      - name: Install chrome
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: python -m scripts.install_chrome_for_ci
      - name: Install ffmpeg
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: sudo apt install ffmpeg
      - name: Run e2e File Upload Features Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: xvfb-run -a --server-args="-screen 0, 1285x1000x24" python -m scripts.run_e2e_tests --suite="fileUploadFeatures" --prod_env
        env: 
          VIDEO_RECORDING_IS_ENABLED: 0
      - name: Run e2e Play Voiceovers Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: xvfb-run -a --server-args="-screen 0, 1285x1000x24" python -m scripts.run_e2e_tests --skip-install --skip-build --suite="playVoiceovers" --prod_env
        env: 
          VIDEO_RECORDING_IS_ENABLED: 0
      - name: Run e2e File Upload Extensions Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: xvfb-run -a --server-args="-screen 0, 1285x1000x24" python -m scripts.run_e2e_tests --skip-install --skip-build --suite="fileUploadExtensions" --prod_env
        env: 
          VIDEO_RECORDING_IS_ENABLED: 0
      - name: Run e2e Contributor Dashboard Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: xvfb-run -a --server-args="-screen 0, 1285x1000x24" python -m scripts.run_e2e_tests --skip-install --skip-build --suite="contributorDashboard" --prod_env
        env:
          VIDEO_RECORDING_IS_ENABLED: 0
      - name: Run e2e Blog Dashboard Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: for run in {1..5}; do xvfb-run -a --server-args="-screen 0, 1285x1000x24" python -m scripts.run_e2e_tests --skip-install --skip-build --suite="blogDashboard" --prod_env; done
        env: 
          VIDEO_RECORDING_IS_ENABLED: 1
      - name: Run e2e Publication Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: xvfb-run -a --server-args="-screen 0, 1285x1000x24" python -m scripts.run_e2e_tests --suite="publication"  --skip-install --skip-build --server_log_level="info" --prod_env
        env: 
          VIDEO_RECORDING_IS_ENABLED: 0
      - name: Run e2e Feature Gating Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: xvfb-run -a --server-args="-screen 0, 1285x1000x24" python -m scripts.run_e2e_tests --skip-install --suite="featureGating"
        env: 
          VIDEO_RECORDING_IS_ENABLED: 0
      - name: Uploading protractor-video as Artifacts
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 && always() }}
        uses: actions/upload-artifact@v2
        with:
          name: protractor-video
          path: /home/runner/work/oppia/protractor-video
      - name: Uploading webdriverio-video as Artifacts
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 && always() }}
        uses: actions/upload-artifact@v2
        with:
          name: webdriverio-video
          path: /home/runner/work/oppia/webdriverio-video
      - name: Uploading protractor screenshots as Artifacts
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 && always() }}
        uses: actions/upload-artifact@v2
        with:
          name: protractor-screenshots
          path: /home/runner/work/oppia/protractor-screenshots
      - name: Uploading webdriverio screenshots as Artifacts
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 && always() }}
        uses: actions/upload-artifact@v2
        with:
          name: webdriverio-screenshots
          path: /home/runner/work/oppia/webdriverio-screenshots
      - name: Uploading webpack bundles as an artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: webpack-bundles
          path: /home/runner/work/oppia/oppia/build
      - name: Checking Memory Usage
        if: ${{ always() }}
        run: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
