name: End-to-End tests
on:
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  e2e_miscellaneous_tests:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
          architecture: 'x64'
      - name: Setup python by installing wheel
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: pip install wheel==0.35.0
      - name: Install third party
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: python -m scripts.install_third_party_libs
      - name: Check if PR is low-risk
        run: |
          python -m scripts.check_if_pr_is_low_risk ${{ github.event.pull_request.html_url }} || false
          echo "low_risk=${?}" >> $GITHUB_ENV
      - name: Install chrome
        if: ${{ env.low_risk != 0 }}
        run: python -m scripts.install_chrome_for_ci
      - name: Run e2e File Upload Features Test
        if: ${{ env.low_risk != 0 }}
        run: xvfb-run -a python -m scripts.run_e2e_tests --suite="fileUploadFeatures" --prod_env
      - name: Run e2e Play Voiceovers Test
        if: ${{ env.low_risk != 0 }}
        run: xvfb-run -a python -m scripts.run_e2e_tests --skip-install --skip-build --suite="playVoiceovers" --prod_env
      - name: Run e2e File Upload Extensions Test
        if: ${{ env.low_risk != 0 }}
        run: xvfb-run -a python -m scripts.run_e2e_tests --skip-install --skip-build --suite="fileUploadExtensions" --prod_env
      - name: Run e2e Contributor Dashboard Test
        if: ${{ env.low_risk != 0 }}
        run: xvfb-run -a python -m scripts.run_e2e_tests --skip-install --skip-build --suite="contributorDashboard" --prod_env
      - name: Run e2e Feature Gating Test
        if: ${{ env.low_risk != 0 }}
        run: xvfb-run -a python -m scripts.run_e2e_tests --skip-install --suite="featureGating"
      - name: Uploading protractor-screenshots as Artifacts
        if: ${{ env.low_risk != 0 }} && always()
        uses: actions/upload-artifact@v2
        with:
          name: protractor-screenshots
          path: /home/runner/work/oppia/protractor-screenshots
