name: Oppiabot

on:
  issues:
    types:
      - labeled

jobs:
  oppiabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Oppiabot
        uses: oppia/oppiabot@1.0.0
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
