name: Send pending review notifications to reviewer on github-discussion
on:
  schedule:
    # Every Tuesday and Thursday at 16:00 UTC.
    - cron: '0 16 * * 2,4'
  # GitHub doesn't provide assurance that the scheduled jobs will run on time
  # (see https://github.community/t/no-assurance-on-scheduled-jobs/133753).
  # So, we add the workflow_dispatch event here to allow triggering this
  # workflow manually if needed.
  workflow_dispatch:

jobs:
  send_notifications:
    name: Send pending review notifications
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install -r src_graphql/requirements.txt
        shell: bash
      - name: Add path to enviornment
        run: echo "PYTHONPATH=${{ github.action_path }}" >> $GITHUB_PATH; echo $GITHUB_PATH
        shell: bash
      - name: Send notification
        run:
          python3 -m src_graphql.index --repo=${{ github.repository }} --token=${{ secrets.DISCUSSION_NOTIFICATION_TOKEN }} --max-wait-hours=48 --verbose
      - name: Report if failed
        if: ${{ failure() }}
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "A pending-review-notification workflow failed."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
